Onboarding
rice-apps/texas-hearing-institute pull request #6
Opened 2023-10-21 20:50 UTC by michelg10

Created onboarding page and `MarkdownText`, `ProgressBar`, and `ToggleGridButtonsComponent` components

2023-10-28 18:42 UTC, pathaks1 commented on texas-hearing-institute/pages/Onboarding1.tsx
> +        <SafeAreaView style={{
SafeAreaView is iOS specific - talk with Paul and Vincent for how they made it Android safe too with React Navigation

2023-10-28 18:44 UTC, pathaks1 commented on texas-hearing-institute/pages/Onboarding2.tsx
same comment on safeareaview for this and rest of onboarding pages; might be nice to take functions like storeItemSelection, retrieveItemSelections, etc and put them into a single function file and use those

2023-10-28 18:45 UTC, pathaks1 requested changes

2023-10-28 18:45 UTC, pathaks1 commented on texas-hearing-institute/pages/Onboarding2.tsx
same comment on safeareaview for this and rest of onboarding pages; might be nice to take functions like storeItemSelection, retrieveItemSelections, etc and put them into a single function file and use those

2023-10-28 18:45 UTC, pathaks1 commented on texas-hearing-institute/pages/Onboarding1.tsx
> +        <SafeAreaView style={{
SafeAreaView is iOS specific - talk with Paul and Vincent for how they made it Android safe too with React Navigation

2023-10-28 19:09 UTC, pathaks1 requested changes

2023-10-28 19:09 UTC, pathaks1 commented on texas-hearing-institute/App.tsx
> +    useEffect(() => {
useEffect should be used for things like side effects; I think it is better design to load in the components in useState itself; please try making this change throughout all the files (I have sent you a screenshot on Slack with an example of how to use async storage within a useState)

2023-11-11 21:18 UTC, baylee-rl approved these changes
looks good! going to merge now. keep working on new branch

2023-11-11 21:18 UTC, baylee-rl commented on texas-hearing-institute/components/CustomSafeAreaView/CustomSafeAreaView.tsx
> +const CustomSafeAreaView: React.FC<CustomSafeAreaViewType> = ({ children }) => {
it's better style to leave out the React.FC typing for functional components

2023-11-11 21:18 UTC, baylee-rl commented on texas-hearing-institute/pages/Onboarding/OnboardingPage.tsx
> +// type RootStackParamList = {
are u going to use all this commented out stuff later? lol

2023-11-11 21:21 UTC, merged